name: categorypicker
version: 2.1.1
description: CategoryPicker is a fork of NumberPicker to support categorical selection via the same UI.
homepage: https://github.com/alecglen/CategoryPicker

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  infinite_listview: ^1.1.0

flutter:
  uses-material-design: true

dev_dependencies:
  flutter_test:
    sdk: flutter