name: widgetpicker
version: 0.1.0
description: WidgetPicker is a fork of NumberPicker to support categorical selection via the same UI.
homepage: https://github.com/alecglen/WidgetPicker

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  infinite_listview: ^1.1.0

flutter:
  uses-material-design: true

dev_dependencies:
  flutter_test:
    sdk: flutter